---
Name: elementalbannerblockconfig
---
SilverStripe\Core\Injector\Injector:
  Link:
    class: SilverStripe\ElementalBannerBlock\ORM\FieldType\DBLink

DNADesign\Elemental\Controllers\ElementController:
  default_styles:
    - silverstripe/elemental-bannerblock:client/dist/styles/frontend-default.css
